name: telerising
services:
  telerising:
    image: qoopido/telerising.minimal:latest
    network_mode: bridge
    ports:
      - target: 5000
        published: "5000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: /DATA/AppData/$AppID/settings.json
        target: /settings.json
    user: $PUID:$PGID
    labels:
      - "com.centurylinklabs.watchtower.scope=telerising"
    x-casaos:
      ports:
        - container: "5000"
          description:
            en_us: WebUI HTTP Port
      volumes:
        - container: /settings.json
          description:
            en_us: The path to your persisted Telerising configuration file (create a file containing just {} for new installs)

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 --scope telerising
    labels:
      - "com.centurylinklabs.watchtower.scope=telerising"

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: telerising
  author: Double-A-92
  category: Media
  description:
    en_us: Telerising is a service that provides an API to generate simple .m3u's from Zattoo & Co.
  developer: dlueth
  icon: https://cdn.jsdelivr.net/gh/Double-A-92/CasaOS-AppStore@main/Apps/Telerising/icon.png
  tips:
    before_install:
      en_us: |
        Create /DATA/AppData/Telerising/settings.json containing just {}.
  title:
    en_us: Telerising
  index: /
  port_map: "5000"
