name: heimdall
services:
  heimdall:
    environment:
      PGID: $PGID                       
      PUID: $PUID                         
      TZ: $TZ                              
    image: linuxserver/heimdall:2.5.6
    labels:
      icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/heimdall-icon.png
    ports:
      - target: 80
        published: "4086"
        protocol: tcp
      - target: 443
        published: "7890"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      ports:
        - container: "80"
          description:
            en_us: Port for http access
        - container: "443"
          description:
            en_us: Port for https access
      volumes:
        - container: /config
          description:
            en_us: Appdata location
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: Double-A-92
  category: WEB
  description:
    en_us: A way to organise all those links to your most used web sites and web
      applications in a simple way. Simplicity is the key to Heimdall. Why not
      use it as your browser start page. It even has the ability to include a
      search bar using either Google, Bing or DuckDuckGo.
  developer: LinuxServer.io
  icon: https://cdn.jsdelivr.net/gh/Double-A-92/CasaOS-AppStore@main/Apps/Heimdall/icon.png
  index: /
  main: heimdall
  port_map: "4086"
  project_url: https://github.com/linuxserver/Heimdall
  scheme: http
  tagline:
    en_us: Heimdall is a way to organise all those links to your most used web sites and web applications in a simple way.
  title:
    en_us: Heimdall
